- hosts: all
  tasks:
  vars:
    apache_create_vhosts: false
    apache_remove_default_vhost: true
    certbot_admin_email: "john.oshi44@gmail.com"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
    - httpd
    certbot_certs:
    - domains:
      - "or.johnoshikoya.com"
    apache_server_name: "or.johnoshikoya.com"
    apache_default_admin_email: "john.oshi44@gmail.com"
    apache_copy_ssl_files: false
    apache_ssl_cert_file_location: "/etc/letsencrypt/live/{{ apache_server_name }}/fullchain.pem"
    apache_ssl_cert_key_location: "/etc/letsencrypt/live/{{ apache_server_name }}/privkey.pem"
    apache_proxy_host: "34.207.119.77"
    apache_proxy_port: 80
    default_context_path: "/"

  - name: Install Prerequisites
    import_role:
      name: ansible-role-prerequisites
    vars:
    - server_name: "{{ inventory_hostname }}"

  roles:
    - ansible-role-apache
    - ansible-role-certbot
    - ansible-role-apache-proxy 
    
  tasks:
  - name: Install Nagiosxi
    import_role:
      name: ansible_role_nagiosxi
 
