- hosts: all
  tasks:
  - name: Install Prerequisites
    import_role:
      name: ansible-role-prerequisites
    vars:
    - server_name: "{{ inventory_hostname }}"

  - name: Install Nagiosxi
    import_role:
      name: ansible_role_nagiosxi


