- hosts: all
  tasks:
  - name: Install Prerequisites
    import_role:
      name: ansible-role-prerequisites

  - name: Install Nagiosxi
    import_role:
      name: ansible_role_nagiosxi

  - name: execute full install
    shell: "./fullinstall -n  "
    args:
      chdir: /home/centos/nagiosxi

  - name: Change Hostname
    import_role:
      name: ansible-role-hostname
    vars:
    - server_name: "{{ inventory_hostname }}"
