---
# tasks file for ansible-role-prerequisites

- name: Install Prerequisites
  yum:
    name:
    - "{{repo_nagios}}"
    - nagiosxi
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install Prerequisites
  package:
    name:
    - "{{repo_nagios}}"
    - nagiosxi
    update_cache: yes
  when: ansible_os_family == 'Debian'
