---
# tasks file for ansible-role-prerequisites

- name: Install Prerequisites
  yum:
    name:
    - vim
    - net-snmp
    - git
    - "{{repo_nagios}}"
    update_cache: yes

- name: Set hostname
  hostname:
    name: "{{ server_name }}"
