- name: Install Prerequisites
  yum:
    name:
    - vim
    - net-snmp
    - git
    - "{{repo_nagios}}"
    - cronie
    - epel-release
    update_cache: yes

- name: Set hostname
  hostname:
    name: "{{ server_name }}"
